## Getting ZIP CODES

# Import the necessary packages
import pandas as pd
from datetime import datetime
from geopy.geocoders import Nominatim
from requests import Request, Session

from google.colab import files
uploaded = files.upload()

# Load the training data
import io
df = pd.read_csv(io.BytesIO(uploaded['miss_data1.csv']))

def nominatim(geocoder: Nominatim):
    session = Session()

    def requester(req, **kwargs):
        req = Request('GET', req, headers=geocoder.headers)
        prepared = req.prepare()
        return session.send(prepared, **kwargs)

    geocoder.urlopen = requester
    return geocoder

def get_zip_codes(locations):
    locator = Nominatim(user_agent="my_geocoder")
    locator = nominatim(locator)
    zip_codes = []
    for latitude, longitude in locations:
        try:
            location = locator.reverse(f"{latitude}, {longitude}")
            if location:
                address = location.address
                address_parts = address.split(',')
                if len(address_parts) >= 2:
                    zip_code = address_parts[-2].strip()
                    zip_codes.append(zip_code)
                else:
                    print("Unexpected address format:", address)
            else:
                print("Location not found for coordinates:", latitude, longitude)
        except Exception as e:
            print("Error during reverse geocoding:", e)
    return zip_codes

# Split the latitude-longitude pairs into batches
batch_size = 1000
batches = [df[['LATITUDE', 'LONGITUDE']][i:i+batch_size] for i in range(0, len(df), batch_size)]

# Apply batch processing to get zip codes
for i, batch in enumerate(batches):
    print(f"Processing batch {i + 1}/{len(batches)}")
    zip_codes = get_zip_codes(batch.values.tolist())
    df.loc[batch.index, 'zip_test'] = zip_codes

df.to_csv('miss_data1.csv', index=False)
files.download('miss_data1.csv')

## Task 2

# Import the necessary packages
import pandas as pd
import numpy as np
from datetime import datetime

# load Motor_Vehicle_Collisions_Crashes.csv
df = pd.read_csv('Motor_Vehicle_Collisions_Crashes.csv')

# load missing_zip_finished.csv
missing_zip = pd.read_csv('missing_zip_finished.csv')

# rename latitude, longitude, and location to lat, long, and loc
missing_zip.rename(columns={'LATITUDE':'lat', 'LONGITUDE':'long'}, inplace=True)

## Correct the data types
# Define a dictionary to specify data types for each column
dtype_options = {
    'CRASH DATE': 'datetime64[ns]',
    'CRASH TIME': 'datetime64[ns]',
    'BOROUGH': 'string',
    'ZIP CODE': 'string',
    'LOCATION': 'string',
    'ON STREET NAME': 'string',
    'CROSS STREET NAME': 'string',
    'OFF STREET NAME': 'string',
    'CONTRIBUTING FACTOR VEHICLE 1': 'string',
    'CONTRIBUTING FACTOR VEHICLE 2': 'string',
    'CONTRIBUTING FACTOR VEHICLE 3': 'string',
    'CONTRIBUTING FACTOR VEHICLE 4': 'string',
    'CONTRIBUTING FACTOR VEHICLE 5': 'string',
    'VEHICLE TYPE CODE 1': 'string',
    'VEHICLE TYPE CODE 2': 'string',
    'VEHICLE TYPE CODE 3': 'string',
    'VEHICLE TYPE CODE 4': 'string',
    'VEHICLE TYPE CODE 5': 'string'
}

# Convert columns to specified data types
df = df.astype(dtype_options)

# replace spaces in column names with underscores
# get the column names in a variable
column_names = df.columns
# replace spaces with underscores
column_names = column_names.str.replace(' ', '_')
# assign the new column names to the dataframe
df.columns = column_names

# In rows where ZIP_CODE is missing, fill in the missing ZIP_CODE using the missing_zip data (by joining on BOROUGH and ON_STREET_NAME)
# merge the dataframes on LOCATION
df = df.merge(missing_zip, on='LOCATION', how='left')

# Using a for loop, when the ZIP_CODE is missing and zip_test is not null, fill in the missing ZIP_CODE using the zip_test value
for i in range(df.shape[0]):
    if pd.isnull(df['ZIP_CODE'][i]):
        if pd.notnull(df['zip_test'][i]):
            df['ZIP_CODE'][i] = df['zip_test'][i]

# drop the zip_test, lat and long columns
df = df.drop(columns=['zip_test', 'lat', 'long'])

# calculate the number of missing values in each column and display the results for each column
missing_values = df.isnull().sum()

# Drop missing rows
# drop rows where ZIP_CODE is null
df = df.dropna(subset=['ZIP_CODE'])
# in the NUMBER_OF_PERSONS_INJURED and NUMBER_OF_PERSONS_KILLED columns, replace NaN with 0
df['NUMBER_OF_PERSONS_INJURED'].fillna(0, inplace=True)
df['NUMBER_OF_PERSONS_KILLED'].fillna(0, inplace=True)
# drop rows where CONTRIBUTING_FACTOR_VEHICLE_1 is null
df = df.dropna(subset=['CONTRIBUTING_FACTOR_VEHICLE_1'])
# drop rows where VEHICLE_TYPE_CODE_1 is null
df = df.dropna(subset=['VEHICLE_TYPE_CODE_1'])

# create a df_borough which only contains ZIP_CODE and BOROUGH
df_borough = df[['ZIP_CODE', 'BOROUGH']]
# create a column that combines ZIP_CODE and BOROUGH
df_borough['ZIP_BOROUGH'] = df_borough['ZIP_CODE'] + ' ' + df_borough['BOROUGH']
# keep only the row where ZIP_BOROUGH is unique
df_borough = df_borough.drop_duplicates(subset='ZIP_BOROUGH')
# drop the ZIP_BOROUGH column
df_borough = df_borough.drop(columns='ZIP_BOROUGH')
df_borough.shape

# save the df_borough to a csv file
df_borough.to_csv('df_borough.csv', index=False)

# drop BOROUGH, LATITUDE, LONGITUDE, LOCATION, ON_STREET_NAME, CROSS_STREET_NAME, OFF_STREET_NAME columns
df = df.drop(columns=['BOROUGH', 'LATITUDE', 'LONGITUDE', 'LOCATION', 'ON_STREET_NAME', 'CROSS_STREET_NAME', 'OFF_STREET_NAME'])

# convert VEHICLE_TYPE_CODE_1, VEHICLE_TYPE_CODE_2, VEHICLE_TYPE_CODE_3, VEHICLE_TYPE_CODE_4, VEHICLE_TYPE_CODE_5 to lowercase
df['VEHICLE_TYPE_CODE_1'] = df['VEHICLE_TYPE_CODE_1'].str.lower()
df['VEHICLE_TYPE_CODE_2'] = df['VEHICLE_TYPE_CODE_2'].str.lower()
df['VEHICLE_TYPE_CODE_3'] = df['VEHICLE_TYPE_CODE_3'].str.lower()
df['VEHICLE_TYPE_CODE_4'] = df['VEHICLE_TYPE_CODE_4'].str.lower()
df['VEHICLE_TYPE_CODE_5'] = df['VEHICLE_TYPE_CODE_5'].str.lower()

vehicle_categories1 = {
    "''lime mope": "Two-wheeler",
    "ceme": "Other",
    ".": "Other",
    "0": "Other",
    "00": "Other",
    "000": "Other",
    "00000": "Other",
    "013": "Other",
    "1": "Other",
    "100th truc": "Truck",
    "11 pa": "Passenger Vehicle",
    "11-va": "Passenger Vehicle",
    "11111": "Other",
    "12 pa": "Passenger Vehicle",
    "12 pass va": "Passenger Vehicle",
    "12 passeng": "Passenger Vehicle",
    "12 fe": "Other",
    "12 passage": "Passenger Vehicle",
    "12' o": "Other",
    "15 pa": "Passenger Vehicle",
    "16m": "Other",
    "17": "Other",
    "18 weeler": "Truck",
    "18 wh": "Other",
    "18 wheeler": "Truck",
    "18 wheel": "Truck",
    "197209": "Other",
    "1s": "Other",
    "2 doo": "Passenger Vehicle",
    "2 dr": "Passenger Vehicle",
    "2 hor": "Other",
    "2 ton": "Truck",
    "2 whe": "Other",
    "2 dr sedan": "Passenger Vehicle",
    "2- to": "Other",
    "2000": "Other",
    "2003": "Other",
    "2015": "Other",
    "250-3": "Other",
    "26 ft": "Other",
    "2ton": "Truck",
    "2ydswheell": "Other",
    "2dr": "Passenger Vehicle",
    "3 whe": "Other",
    "3 wheel sc": "Other",
    "3 doo": "Passenger Vehicle",
    "3-door": "Passenger Vehicle",
    "3-whe": "Other",
    "315 e": "Other",
    "35 ft": "Other",
    "38ab-": "Other",
    "3dc-": "Other",
    "3door": "Passenger Vehicle",
    "4 run": "Passenger Vehicle",
    "4 axe": "Other",
    "4 dr sedan": "Passenger Vehicle",
    "4 wheeler": "Other",
    "430": "Other",
    "4d": "Other",
    "4dr": "Passenger Vehicle",
    "4ds": "Other",
    "4door": "Passenger Vehicle",
    "4dsd": "Other",
    "4whee": "Other",
    "5": "Other",
    "50 cc moto": "Two-wheeler",
    "50cc scoot": "Two-wheeler",
    "50cc mini": "Two-wheeler",
    "52? t": "Other",
    "5x8 t": "Other",
    "600aj": "Other",
    "7": "Other",
    "72000": "Other",
    "7532433": "Other",
    "787": "Other",
    "8x20": "Other",
    "985": "Other",
    "994": "Other",
    "997": "Other",
    "999": "Other",
    "9999": "Other",
    "99999": "Other",
    "?omme": "Other",
    "a bulance": "Emergency Vehicle",
    "a,n": "Other",
    "a-one": "Other",
    "abmu": "Other",
    "abula": "Other",
    "abulance": "Emergency Vehicle",
    "accee": "Other",
    "acces": "Other",
    "access a r": "Other",
    "aeria": "Other",
    "aerial lif": "Other",
    "alumi": "Other",
    "am/tr": "Other",
    "amabu": "Other",
    "amazon spr": "Other",
    "amazon van": "Commercial Vehicle",
    "amb": "Emergency Vehicle",
    "ambalance": "Emergency Vehicle",
    "ambluance": "Emergency Vehicle",
    "ambu": "Emergency Vehicle",
    "ambukance": "Emergency Vehicle",
    "ambul": "Emergency Vehicle",
    "ambulace": "Emergency Vehicle",
    "ambulamce": "Emergency Vehicle",
    "ambulance": "Emergency Vehicle",
    "ambulance`": "Emergency Vehicle",
    "ambulane": "Emergency Vehicle",
    "ambulanve": "Emergency Vehicle",
    "ambulcance": "Emergency Vehicle",
    "ambulence": "Emergency Vehicle",
    "ambulette": "Emergency Vehicle",
    "amubl": "Emergency Vehicle",
    "amubulance": "Emergency Vehicle",
    "amula": "Other",
    "amulance": "Emergency Vehicle",
    "ap": "Other",
    "aport": "Other",
    "app": "Other",
    "app c": "Other",
    "appor": "Other",
    "apurp": "Other",
    "arcimoto": "Other",
    "ariel": "Other",
    "armor": "Other",
    "army": "Other",
    "aspha": "Other",
    "asphalt ro": "Other",
    "autotrlr t": "Other",
    "all-terrain vehicle": "Other",
    "amazon tru": "Commercial Vehicle",
    "ambiance": "Other",
    "armored truck": "Commercial Vehicle",
    "attac": "Other",
    "b5-44": "Other",
    "b55 excava": "Other",
    "back": "Other",
    "back hoe": "Other",
    "backh": "Other",
    "backhoe lo": "Other",
    "bed t": "Other",
    "beyond sco": "Two-wheeler",
    "bicyc": "Two-wheeler",
    "bicycle": "Two-wheeler",
    "bk": "Other",
    "bkhoe": "Other",
    "black": "Other",
    "block": "Other",
    "blu bus": "Commercial Vehicle",
    "blue": "Other",
    "blue chevy": "Passenger Vehicle",
    "boat": "Other",
    "bob c": "Other",
    "bob cat": "Other",
    "bobca": "Other",
    "bobcat": "Other",
    "bobcat for": "Other",
    "bobcat/for": "Other",
    "boom": "Other",
    "boom 60ft": "Other",
    "boom lift": "Other",
    "boom lift/": "Other",
    "boom moped": "Two-wheeler",
    "booml": "Other",
    "box": "Other",
    "box car": "Commercial Vehicle",
    "box h": "Other",
    "box t": "Other",
    "box truck": "Commercial",
    'sedan': 'Passenger Vehicle',
    'station wagon/sport utility vehicle': 'Passenger Vehicle',
    'tanker': 'Commercial Vehicle',
    'Passenger Vehicle': 'Passenger Vehicle',
    'taxi': 'Passenger Vehicle',
    'van': 'Utility Vehicle',
    'e-bike': 'Two-wheeler',
    'Emergency Vehicle': 'Emergency Vehicle',
    'bike': 'Two-wheeler',
    'Commercial': 'Commercial Vehicle',
    'motorcycle': 'Two-wheeler',
    'e-scooter': 'Two-wheeler',
    'pick-up truck': 'Truck',
    'convertible': 'Passenger Vehicle',
    'tractor truck diesel': 'Truck',
    'flat bed': 'Truck',
    'tow truck / wrecker': 'Truck',
    'dump': 'Truck',
    '�mbu': 'Other',
    'pk': 'Other',
    'moped': 'Two-wheeler',
    'trailer': 'Truck',
    'school bus': 'Passenger Vehicle',
    'lift boom': 'Utility Vehicle',
    'scooter': 'Two-wheeler',
    'cater': 'Other',
    'pkup': 'Other',
    'beverage truck': 'Commercial Vehicle',
    'semi trail': 'Truck',
    'tow truck': 'Truck',
    'motorbike': 'Two-wheeler',
    'unknown': 'Other',
    'lunch wagon': 'Commercial Vehicle',
    'flat rack': 'Truck',
    'carry all': 'Utility Vehicle',
    'unk': 'Other',
    'uspcs': 'Other',
    'tractor truck gasoline': 'Truck',
    'garbage tr': 'Utility Vehicle',
    'minicycle': 'Two-wheeler',
    'Commercial Vehicle': 'Commercial Vehicle',
    'usps truck': 'Commercial Vehicle',
    'chassis cab': 'Truck',
    'bulk agriculture': 'Commercial Vehicle',
    'motorscooter': 'Two-wheeler',
    'utility': 'Utility Vehicle',
    'concrete mixer': 'Truck',
    'open body': 'Utility Vehicle',
    'excavator': 'Utility Vehicle',
    'fork lift': 'Utility Vehicle',
    'street swe': 'Utility Vehicle',
    'commercial': 'Commercial Vehicle',
    'psd': 'Other',
    'pick up': 'Utility Vehicle',
    'mta': 'Other',
    'multi-wheeled vehicle': 'Utility Vehicle',
    'e bike uni': 'Two-wheeler',
    'truck': 'Truck',
    'mack': 'Truck',
    'refrigerated van': 'Utility Vehicle',
    'stake or rack': 'Truck',
    'work van': 'Utility Vehicle',
    'motor scoo': 'Two-wheeler',
    'pickup tru': 'Utility Vehicle',
    'carrier': 'Utility Vehicle',
    'usps': 'Commercial Vehicle',
    'department': 'Commercial Vehicle',
    'nypd van': 'Utility Vehicle',
    'pallet': 'Utility Vehicle',
    'self': 'Utility Vehicle',
    'mailtruck': 'Commercial Vehicle',
    'tank': 'Commercial Vehicle',
    'pick up tr': 'Utility Vehicle',
    'hopper': 'Commercial Vehicle',
    'mopad': 'Two-wheeler',
    'postal ser': 'Commercial Vehicle',
    'sanmen cou': 'Other',
    'pump': 'Commercial Vehicle',
    'dirt bike': 'Two-wheeler',
    'shuttle bu': 'Passenger Vehicle',
    'nys ambula': 'Emergency Vehicle',
    'van camper': 'Utility Vehicle',
    'rv': 'Utility Vehicle',
    'uhal': 'Other',
    'livestock rack': 'Utility Vehicle',
    'Other': 'Other',
    'pickup': 'Utility Vehicle',
    'dodge': 'Passenger Vehicle',
    'Two-wheeler': 'Two-wheeler',
    'fire appar': 'Emergency Vehicle',
    'mini van': 'Passenger Vehicle',
    'road sweep': 'Utility Vehicle',
    'self insur': 'Utility Vehicle',
    'van/truck': 'Utility Vehicle',
    'street cle': 'Utility Vehicle',
    'lift': 'Utility Vehicle',
    'kick scoot': 'Two-wheeler',
    'semi': 'Truck',
    'mta bus': 'Passenger Vehicle',
    'pumper': 'Emergency Vehicle',
    'pas': 'Other',
    'truck comm': 'Commercial Vehicle',
    'cement tru': 'Commercial Vehicle',
    'delivery t': 'Commercial Vehicle',
    'enclosed body - nonremovable enclosure': 'Utility Vehicle',
    'fdny truck': 'Emergency Vehicle',
    'skywatch': 'Emergency Vehicle',
    'pedicab': 'Passenger Vehicle',
    'sprinter v': 'Utility Vehicle',
    'tl': 'Other',
    'mack truck': 'Truck',
    'minibike': 'Two-wheeler',
    'fdny fire': 'Emergency Vehicle',
    'tcn': 'Other',
    'snow plow': 'Utility Vehicle',
    'unk box tr': 'Other',
    'horse trai': 'Utility Vehicle',
    'tf': 'Other',
    'escooter s': 'Two-wheeler',
    'motor home': 'Utility Vehicle',
    'refg': 'Utility Vehicle',
    'camper van': 'Utility Vehicle',
    'utility ve': 'Utility Vehicle',
    'power shov': 'Utility Vehicle',
    'passenger': 'Passenger Vehicle',
    'tr': 'Other',
    'grumman ll': 'Utility Vehicle',
    'cat forkli': 'Utility Vehicle',
    'utility tr': 'Utility Vehicle',
    'white van': 'Utility Vehicle',
    'dent and s': 'Utility Vehicle',
    'motorized home': 'Utility Vehicle',
    'pick wh': 'Utility Vehicle',
    'usps mail': 'Commercial Vehicle',
    'crane boom': 'Utility Vehicle',
    'pc': 'Other',
    'city': 'Other',
    'nypd tow t': 'Utility Vehicle',
    'work truck': 'Utility Vehicle',
    'usps posta': 'Commercial Vehicle',
    'nyc sanita': 'Utility Vehicle',
    'gas scoote': 'Two-wheeler',
    'vms': 'Other',
    'flatbed': 'Truck',
    'dodge ram': 'Passenger Vehicle',
    'suburban': 'Passenger Vehicle',
    'unmarked v': 'Utility Vehicle',
    'm2': 'Other',
    'locomotive': 'Utility Vehicle',
    'cherv': 'Other',
    'post offic': 'Utility Vehicle',
    'skateboard': 'Other',
    'motorized': 'Other',
    'enclosed body - removable enclosure': 'Other',
    'ram': 'Truck',
    'tlr': 'Other',
    'moving tru': 'Truck',
    'verzion va': 'Other',
    'yamaha': 'Two-wheeler',
    'school  bu': 'Other',
    'nonmotords': 'Other',
    'mini bus': 'Passenger Vehicle',
    'motorscoot': 'Two-wheeler',
    'police rep': 'Emergency Vehicle',
    'ec3': 'Other',
    'sedona': 'Passenger Vehicle',
    'tlc': 'Other',
    'fdny ladde': 'Emergency Vehicle',
    'mopd': 'Other',
    'sanitation': 'Utility Vehicle',
    'utility va': 'Utility Vehicle',
    'gas powere': 'Other',
    'util': 'Utility Vehicle',
    'pas (4dr s': 'Passenger Vehicle',
    'horse carr': 'Other',
    'ups': 'Commercial Vehicle',
    'backhoe': 'Other',
    'engine sp0': 'Other',
    'pass': 'Passenger Vehicle',
    'usps small': 'Commercial Vehicle',
    'pickup with mounted camper': 'Truck',
    'us mail tr': 'Commercial Vehicle',
    'street': 'Other',
    'gas mo ped': 'Two-wheeler',
    'scooter ga': 'Two-wheeler',
    'postal tru': 'Commercial Vehicle',
    'pro master': 'Commercial Vehicle',
    'rgr': 'Other',
    'us postal': 'Commercial Vehicle',
    'van wh': 'Commercial Vehicle',
    'suv': 'Passenger Vehicle',
    'freight tr': 'Truck',
    'emt ambula': 'Emergency Vehicle',
    'food cart': 'Other',
    'tk': 'Other',
    'toyota': 'Passenger Vehicle',
    'spr': 'Other',
    'mini schoo': 'Passenger Vehicle',
    'u-haul min': 'Commercial Vehicle',
    'ford picku': 'Truck',
    'nyc transi': 'Other',
    'nyc parks': 'Other',
    'tractor': 'Other',
    'ups truck': 'Commercial Vehicle',
    'nycha van': 'Commercial Vehicle',
    'usps van': 'Commercial Vehicle',
    'house on w': 'Other',
    'transit': 'Other',
    'nypd': 'Emergency Vehicle',
    'backhoe re': 'Other',
    'f550': 'Truck',
    'yw school': 'Passenger Vehicle',
    'well driller': 'Other',
    'mail truck': 'Commercial Vehicle',
    'u-haul': 'Commercial Vehicle',
    'tractor tr': 'Other',
    'moped 150c': 'Two-wheeler',
    'fedex truc': 'Commercial Vehicle',
    'f550 esu r': 'Emergency Vehicle',
    'other': 'Other',
    'stak': 'Other',
    'van truck': 'Commercial Vehicle',
    'yellow tax': 'Passenger Vehicle',
    'tow': 'Other',
    'nj transit': 'Other',
    'schoolbus': 'Passenger Vehicle',
    'usps  van': 'Commercial Vehicle',
    'fed ex tru': 'Commercial Vehicle',
    'minivan': 'Passenger Vehicle',
    'city of ne': 'Other',
    'fedex box': 'Commercial Vehicle',
    'ny city mt': 'Other',
    'pick-up tr': 'Truck',
    'promaster': 'Commercial Vehicle',
    'trolley ri': 'Passenger Vehicle',
    'sprinter w': 'Commercial Vehicle',
    'com delive': 'Commercial Vehicle',
    'rmp': 'Emergency Vehicle',
    'mail': 'Commercial Vehicle',
    'limousine': 'Passenger Vehicle',
    'e bike w p': 'Two-wheeler',
    'crane': 'Other',
    'nyc fire t': 'Emergency Vehicle',
    'power ladd': 'Utility Vehicle',
    'mercedes': 'Passenger Vehicle',
    'oml/omnibu': 'Other',
    'vanette': 'Commercial Vehicle',
    'trac': 'Other',
    'nyc ambula': 'Emergency Vehicle',
    'trailer/fl': 'Other',
    'postal veh': 'Commercial Vehicle',
    'flat': 'Other',
    'subn - amb': 'Passenger Vehicle',
    'spark150 s': 'Two-wheeler',
    'trailee': 'Other',
    'special co': 'Other',
    'quality tr': 'Other',
    'sanitaion': 'Utility Vehicle',
    'ram promas': 'Commercial Vehicle',
    'skid loade': 'Other',
    'marked van': 'Commercial Vehicle',
    'bulldozer': 'Other',
    'nynj rail': 'Other',
    'truck trai': 'Truck',
    'trk': 'Other',
    'fdny ems': 'Emergency Vehicle',
    'mta truck': 'Commercial Vehicle',
    'niu': 'Other',
    'usps truc,': 'Commercial Vehicle',
    'na': 'Other',
    'firet truc': 'Emergency Vehicle',
    'utility wh': 'Utility Vehicle',
    'u haul tru': 'Commercial Vehicle',
    'subr': 'Other',
    'trailor': 'Other',
    'nyc ems': 'Emergency Vehicle',
    'rep': 'Other',
    'refuse tru': 'Utility Vehicle',
    'flat bed t': 'Truck',
    'ladder tru': 'Utility Vehicle',
    'sanitaton': 'Utility Vehicle',
    'e-skateboa': 'Two-wheeler',
    'usps 88716': 'Commercial Vehicle',
    'perm': 'Other',
    'forlift': 'Other',
    'motor skat': 'Other',
    'can': 'Other',
    'flatbed fr': 'Truck',
    'postal van': 'Commercial Vehicle',
    'firtruck': 'Emergency Vehicle',
    'ttailer': 'Other',
    'usps/govt': 'Commercial Vehicle',
    'truck van': 'Commercial Vehicle',
    'catapillar': 'Other',
    'swt': 'Other',
    'flat  bed': 'Truck',
    'courier': 'Commercial Vehicle',
    'smart car': 'Passenger Vehicle',
    'message si': 'Other',
    'e-unicycle': 'Two-wheeler',
    'almbulance': 'Emergency Vehicle',
    'dark color': 'Other',
    'fd ladder': 'Emergency Vehicle',
    'oth': 'Other',
    'chevy expr': 'Passenger Vehicle',
    'slingshot': 'Passenger Vehicle',
    'dilevery t': 'Commercial Vehicle',
    'freight fl': 'Truck',
    'unkn': 'Other',
    'moving van': 'Truck',
    'horse': 'Other',
    'truck flat': 'Truck',
    'delivery v': 'Commercial Vehicle',
    'dot equipm': 'Other',
    'wh ford co': 'Other',
    'light trai': 'Other',
    'ut': 'Utility Vehicle',
    'cross': 'Other',
    'bucket tru': 'Truck',
    'f-250': 'Truck',
    'mechanical': 'Other',
    'nyc fd': 'Emergency Vehicle',
    'fusion': 'Passenger Vehicle',
    'lcomm': 'Commercial Vehicle',
    'e skate bo': 'Two-wheeler',
    'trc': 'Other',
    'postal bus': 'Commercial Vehicle',
    'hrse': 'Other',
    'cat': 'Other',
    'white ambu': 'Emergency Vehicle',
    'utility.': 'Utility Vehicle',
    'trail': 'Other',
    'trl': 'Other',
    'freig delv': 'Commercial Vehicle',
    'delviery': 'Commercial Vehicle',
    'e-bik': 'Two-wheeler',
    'escavator': 'Other',
    'omr': 'Other',
    'p/sh': 'Other',
    'pick': 'Other',
    'usps #7530': 'Commercial Vehicle',
    'hearse': 'Emergency Vehicle',
    'se': 'Other',
    'push scoot': 'Two-wheeler',
    'nat grid t': 'Utility Vehicle',
    'yellow cab': 'Passenger Vehicle',
    'wagon': 'Other',
    't880': 'Truck',
    'pay loader': 'Other',
    'oms': 'Other',
    'rv/van': 'Utility Vehicle',
    'tr-trailer': 'Truck',
    'esu rescue': 'Emergency Vehicle',
    'ttrailer': 'Truck',
    'i-haul': 'Truck',
    'yellowpowe': 'Other',
    'posta': 'Commercial Vehicle',
    'utili': 'Utility Vehicle',
    'schoo': 'Other',
    'tow t': 'Truck',
    'e-sco': 'Two-wheeler',
    'towe truck': 'Truck',
    'st': 'Other',
    'unkno': 'Other',
    'firet': 'Emergency Vehicle',
    'e bik': 'Two-wheeler',
    'psh': 'Other',
    'us po': 'Commercial Vehicle',
    'tract': 'Other',
    'uhual': 'Truck',
    'scoot': 'Two-wheeler',
    'picku': 'Other',
    'forkl': 'Other',
    'van t': 'Utility Vehicle',
    'skate': 'Other',
    'paylo': 'Other',
    'sanit': 'Utility Vehicle',
    'econo': 'Passenger Vehicle',
    'van/t': 'Utility Vehicle',
    'fuel': 'Other',
    'tanke': 'Other',
    'sprin': 'Other',
    'road': 'Other',
    'dot t': 'Truck',
    'mta b': 'Passenger Vehicle',
    'flat/': 'Other',
    'food': 'Other',
    'comme': 'Commercial Vehicle',
    'stree': 'Other',
    'cab': 'Passenger Vehicle',
    'usp m': 'Commercial Vehicle',
    'santi': 'Utility Vehicle',
    'prks': 'Other',
    'g spc': 'Other',
    'cont': 'Other',
    'cat.': 'Other',
    'polic': 'Emergency Vehicle',
    'parce': 'Other',
    'comm': 'Commercial Vehicle',
    'golf': 'Passenger Vehicle',
    'wineb': 'Other',
    'pu': 'Other',
    'boxtr': 'Truck',
    'towtr': 'Truck',
    'pick-': 'Other',
    'power': 'Other',
    'mini': 'Passenger Vehicle',
    'trlr': 'Other',
    'fork': 'Other',
    'vespa': 'Two-wheeler',
    'mobil': 'Other',
    'uhaul': 'Truck',
    'excav': 'Other',
    'f650': 'Truck',
    'skid-': 'Other',
    'e sco': 'Two-wheeler',
    'motor': 'Other',
    'nys a': 'Other',
    'range': 'Passenger Vehicle',
    'lmb': 'Other',
    'bulld': 'Other',
    'van (': 'Utility Vehicle',
    'flatb': 'Truck',
    'subn': 'Passenger Vehicle',
    'comm.': 'Commercial Vehicle',
    'white': 'Other',
    'unkow': 'Other',
    'btm': 'Other',
    'nttrl': 'Other',
    'yello': 'Other',
    'movin': 'Truck',
    'subur': 'Passenger Vehicle',
    'rescu': 'Emergency Vehicle',
    'couri': 'Other',
    'e - b': 'Two-wheeler',
    'navig': 'Passenger Vehicle',
    'tir': 'Other',
    'track exca': 'Other',
    'concr': 'Other',
    'cat p': 'Other',
    'passe': 'Passenger Vehicle',
    'dirt': 'Other',
    'segwa': 'Two-wheeler',
    'sc': 'Other',
    'sea': 'Other',
    'moter': 'Other',
    'u-hau': 'Truck',
    'bucke': 'Other',
    'nycha': 'Passenger Vehicle',
    'snow': 'Other',
    'comer': 'Commercial Vehicle',
    'spc': 'Other',
    'tktr': 'Other',
    'vav': 'Other',
    'none': 'Other',
    'gover': 'Other',
    'te': 'Other',
    'ltrl': 'Other',
    '\x7fomm': 'Other',
    'trans': 'Other',
    'track': 'Other',
    'mac t': 'Other',
    'ups t': 'Other',
    'nissa': 'Passenger Vehicle',
    'log': 'Other',
    'red t': 'Other',
    'usps2': 'Commercial Vehicle',
    'nyc d': 'Passenger Vehicle',
    'winne': 'Other',
    'uspos': 'Commercial Vehicle',
    'mc': 'Other',
    'ems a': 'Emergency Vehicle',
    'diese': 'Other',
    'budge': 'Other',
    'grain': 'Other',
    'sweep': 'Other',
    'omnib': 'Other',
    'fed e': 'Other',
    'me/be': 'Other',
    'push': 'Other',
    'chevy': 'Passenger Vehicle',
    'comix': 'Commercial Vehicle',
    'van a': 'Utility Vehicle',
    'tower': 'Utility Vehicle',
    'mark': 'Other',
    'emrgn': 'Emergency Vehicle',
    'roads': 'Other',
    'rd/s': 'Other',
    'work': 'Other',
    'workh': 'Other',
    'cherr': 'Other',
    'utv': 'Utility Vehicle',
    'nyc': 'Other',
    'loade': 'Truck',
    'ns am': 'Other',
    'new y': 'Other',
    'front': 'Other',
    'camp': 'Other',
    'rgs': 'Other',
    'posto': 'Other',
    'r/v c': 'Other',
    'cat 9': 'Other',
    'e-mot': 'Two-wheeler',
    'fork-': 'Other',
    'wheel': 'Other',
    'case': 'Other',
    'liber': 'Other',
    'comb': 'Other',
    'r/v': 'Other',
    'dema-': 'Other',
    'cart': 'Other',
    'trlr plt,': 'Other',
    'spec': 'Other',
    'seagr': 'Other',
    'van/b': 'Other',
    'chart': 'Other',
    'nyc m': 'Other',
    'mcy': 'Two-wheeler',
    'icecr': 'Other',
    'omt': 'Other',
    'tow-t': 'Other',
    'ulili': 'Other',
    'cargo': 'Truck',
    'smart': 'Other',
    'nyc a': 'Other',
    'e amb': 'Emergency Vehicle',
    'highl': 'Other',
    'e-350': 'Other',
    'marke': 'Other',
    'veriz': 'Other',
    'van w': 'Other',
    'sprinter': 'Other',
    'passa': 'Passenger Vehicle',
    'c0mme': 'Commercial Vehicle',
    'oil t': 'Other',
    'self-': 'Other',
    'u.s. posta': 'Other',
    'refri': 'Other',
    'e one': 'Other',
    'bsd': 'Other',
    'tr/ki': 'Truck',
    'semi-': 'Truck',
    'e3': 'Other',
    'bucketload': 'Other',
    'mecha': 'Other',
    'free': 'Other',
    'liver': 'Other',
    'rubbe': 'Other',
    'carri': 'Other',
    'dp': 'Other',
    'p/se': 'Other',
    'oml': 'Other',
    'nyc bus': 'Other',
    'ladde': 'Other',
    'omni': 'Other',
    'nyc f': 'Other',
    'pedic': 'Other',
    'renta': 'Other',
    'cemen': 'Other',
    'st150': 'Other',
    'tan p': 'Other',
    'small': 'Other',
    'pavin': 'Other',
    'mo pa': 'Other',
    'east': 'Other',
    'priva': 'Other',
    'sfi': 'Other',
    'livery bus': 'Commercial Vehicle',
    'sterl': 'Other',
    'sd': 'Other',
    'tl tr': 'Truck',
    'tram': 'Other',
    'cabin': 'Other',
    'mta u': 'Other',
    'tailg': 'Other',
    'dirtb': 'Two-wheeler',
    'del': 'Other',
    'nt tr': 'Truck',
    'stack': 'Other',
    'nycta': 'Other',
    'token': 'Other',
    'mtr s': 'Other',
    'dolly': 'Other',
    'oz mo': 'Other',
    'delie': 'Other',
    'bobct': 'Other',
    'c3': 'Other',
    'mcy b': 'Two-wheeler',
    'catip': 'Other',
    'progr': 'Other',
    'mvp': 'Other',
    'miniv': 'Passenger Vehicle',
    'car c': 'Passenger Vehicle',
    'ringo': 'Other',
    'rmb': 'Other',
    'yw po': 'Other',
    'pet': 'Other',
    'semi-trail': 'Truck',
    'mo pe': 'Other',
    'yamah': 'Two-wheeler',
    'u hau': 'Truck',
    'pois': 'Other',
    'feig': 'Other',
    'mta c': 'Other',
    'ladder 34': 'Other',
    'depar': 'Other',
    'sudn': 'Other',
    'f15': 'Other',
    'ss': 'Other',
    'shove': 'Other',
    'unkown': 'Other',
    'tcm': 'Other',
    'vab': 'Other',
    'sw': 'Other',
    'pumpe': 'Other',
    'repai': 'Other',
    'eamb': 'Emergency Vehicle',
    'utlit': 'Other',
    'scoo': 'Two-wheeler',
    'snowmobile': 'Other',
    'rood': 'Other',
    'sybn': 'Other',
    'plow': 'Other',
    'usps # 487': 'Other',
    'fedx': 'Other',
    'stake': 'Other',
    'us': 'Other',
    'vpg': 'Other',
    'amdu': 'Other',
    'atv p': 'Other',
    'trac.': 'Other',
    'conve': 'Other',
    'sub': 'Other',
    'olc': 'Other',
    'scomm': 'Other',
    'maxim': 'Other',
    'ps': 'Other',
    't/ cr': 'Other',
    'swepe': 'Other',
    'sport utility / station wagon': 'Passenger Vehicle',
    'e tow': 'Emergency Vehicle',
    'omt/t': 'Other',
    'scl': 'Other',
    'house': 'Other',
    'conta': 'Other',
    'ems b': 'Emergency Vehicle',
    'fr`': 'Other',
    'ltr': 'Other',
    'tr/tr': 'Truck',
    'scooc': 'Two-wheeler',
    'yy': 'Other',
    'rv/tr': 'Other',
    'psp': 'Other',
    'gokar': 'Other',
    'e- bi': 'Emergency Vehicle',
    'us ma': 'Other',
    'servi': 'Other',
    'sm yw': 'Other',
    'hosre': 'Other',
    'nyfd': 'Emergency Vehicle',
    'trali': 'Truck',
    'engin': 'Other',
    'dhl t': 'Other',
    'nyu s': 'Other',
    'dl': 'Passenger Vehicle',
    'util truck': 'Truck',
    'private': 'Passenger Vehicle',
    'wheelchair': 'Other',
    'nice bus': 'Commercial Vehicle',
    'bmw': 'Passenger Vehicle',
    'escootersi': 'Two-wheeler',
    'wh': 'Other',
    'dirtbike': 'Two-wheeler',
    'unknown ve': 'Other',
    'mta nyc bu': 'Commercial Vehicle',
    'freight to': 'Commercial Vehicle',
    'mtabus': 'Commercial Vehicle',
    'skatboard': 'Two-wheeler',
    'toolcat': 'Utility Vehicle',
    'revel scoo': 'Two-wheeler',
    'crane truc': 'Truck',
    'unknow': 'Other',
    'uhaul truc': 'Truck',
    'nycfiredep': 'Emergency Vehicle',
    'cat payloa': 'Truck',
    "revel mo'e": 'Two-wheeler',
    'dot vehicl': 'Commercial Vehicle',
    'escavater': 'Commercial Vehicle',
    'm21': 'Passenger Vehicle',
    'special pu': 'Commercial Vehicle',
    'bay crane': 'Truck',
    'gas bicycl': 'Two-wheeler',
    'usps mailt': 'Commercial Vehicle',
    'pedestrian': 'Other',
    'truck ladd': 'Truck',
    'moped clas': 'Two-wheeler',
    'orange jlg': 'Other',
    'van box tr': 'Truck',
    'limit use': 'Other',
    'food deliv': 'Commercial Vehicle',
    'stake truc': 'Truck',
    'priv ambul': 'Emergency Vehicle',
    'e skateboa': 'Two-wheeler',
    'unk female': 'Other',
    'scooter no': 'Two-wheeler',
    'dump gr': 'Truck',
    'nypd esu t': 'Emergency Vehicle',
    'ups van': 'Commercial Vehicle',
    'busv': 'Commercial Vehicle',
    'dollar van': 'Commercial Vehicle',
    'ride on sc': 'Two-wheeler',
    'chevy carg': 'Commercial Vehicle',
    'uknown': 'Other',
    'fire depar': 'Emergency Vehicle',
    'cargo trai': 'Truck',
    'gmc delive': 'Commercial Vehicle',
    'x trailer': 'Truck',
    'u haul': 'Commercial Vehicle',
    'skate boar': 'Two-wheeler',
    'engine': 'Other',
    'mo ped': 'Two-wheeler',
    'moped scoo': 'Two-wheeler',
    'wheel load': 'Truck',
    'fed ex van': 'Commercial Vehicle',
    'delivery w': 'Commercial Vehicle',
    'oil tanker': 'Commercial Vehicle',
    'gas mo-ped': 'Two-wheeler',
    'short scho': 'Passenger Vehicle',
    'bobcat sno': 'Utility Vehicle',
    'utility ca': 'Utility Vehicle',
    'pedi cab': 'Two-wheeler',
    'komatsu lo': 'Commercial Vehicle',
    'camper tra': 'Other',
    'mopet': 'Two-wheeler',
    'lateral tr': 'Truck',
    'detached t': 'Other',
    'segway': 'Two-wheeler',
    'transit mt': 'Passenger Vehicle',
    'emt truck': 'Emergency Vehicle',
    'embulance': 'Emergency Vehicle',
    'back ho': 'Truck',
    'trailer tr': 'Truck',
    'mcr': 'Other',
    'trailer no': 'Truck',
    'swingloade': 'Truck',
    'moped bike': 'Two-wheeler',
    'u-haul tru': 'Commercial Vehicle',
    't350hd': 'Commercial Vehicle',
    'cherry pic': 'Other',
    'unicycle': 'Two-wheeler',
    'mta work t': 'Commercial Vehicle',
    'p/u': 'Commercial Vehicle',
    'train cart': 'Other',
    'towtruck': 'Emergency Vehicle',
    'stand up s': 'Two-wheeler',
    'toolcat fo': 'Utility Vehicle',
    'mop pad': 'Two-wheeler',
    'charter bu': 'Commercial Vehicle',
    'f45': 'Passenger Vehicle',
    'bull dozer': 'Other',
    'red vehicl': 'Passenger Vehicle',
    'citibike': 'Two-wheeler',
    'nyc fire d': 'Emergency Vehicle',
    'nyc truck': 'Commercial Vehicle',
    'n/a': 'Other',
    'ecoline va': 'Commercial Vehicle',
    'new flyer': 'Commercial Vehicle',
    'mobility s': 'Other',
    'gas bike': 'Two-wheeler',
    'refriger t': 'Commercial Vehicle',
    'nyc fdny': 'Emergency Vehicle',
    'cat caterp': 'Other',
    'u haul mov': 'Commercial Vehicle',
    'motor dirt': 'Two-wheeler',
    'util.': 'Utility Vehicle',
    'caterpilla': 'Other',
    'uni e-bike': 'Two-wheeler',
    'basic psd': 'Passenger Vehicle',
    'for van': 'Commercial Vehicle',
    'mta bus  4': 'Commercial Vehicle',
    'roadroller': 'Commercial Vehicle',
    'motored sc': 'Two-wheeler',
    'rental tru': 'Commercial Vehicle',
    'school van': 'Commercial Vehicle',
    'cadet': 'Other',
    'tow trick': 'Emergency Vehicle',
    'fed ex': 'Commercial Vehicle',
    'const equi': 'Other',
    'subn tn': 'Passenger Vehicle',
    'bobcat 216': 'Utility Vehicle',
    'uspcs truc': 'Commercial Vehicle',
    'command po': 'Other',
    'plow  truc': 'Truck',
    'plow truck': 'Truck',
    'usps self': 'Commercial Vehicle',
    'e- motor b': 'Two-wheeler',
    'rented boo': 'Other',
    'workh util': 'Utility Vehicle',
    'wheel barr': 'Other',
    'ny ems': 'Emergency Vehicle',
    'uhaul box': 'Commercial Vehicle',
    'e-sooter': 'Two-wheeler',
    'truck cran': 'Truck',
    'car traile': 'Other',
    'left the s': 'Other',
    'folk lift': 'Other',
    'tilt tande': 'Other',
    'nyc acs va': 'Commercial Vehicle',
    'escooter': 'Two-wheeler',
    'mobile': 'Other',
    'vehicle 2': 'Other',
    'palfinger': 'Other',
    'nyc firetr': 'Emergency Vehicle',
    'pick truck': 'Truck',
    'rds': 'Other',
    'e-scoter': 'Two-wheeler',
    'van/transi': 'Truck',
    'glp050vxev': 'Other',
    'tree cutte': 'Utility Vehicle',
    't630 forkl': 'Utility Vehicle',
    'escovator': 'Utility Vehicle',
    'cargo truc': 'Truck',
    'itas': 'Other',
    'tour bus': 'Passenger Vehicle',
    'flatbed tr': 'Truck',
    'armored tr': 'Truck',
    'tow trk': 'Truck',
    'short bus': 'Passenger Vehicle',
    'buldozer': 'Utility Vehicle',
    'pick rd': 'Truck',
    'nyc dot': 'Commercial Vehicle',
    'pumper tru': 'Commercial Vehicle',
    'spinter va': 'Commercial Vehicle',
    'tank wh': 'Truck',
    'livery omn': 'Commercial Vehicle',
    'hino tank': 'Truck',
    'postal car': 'Commercial Vehicle',
    'scotter': 'Two-wheeler',
    'vendor cha': 'Commercial Vehicle',
    'mobile foo': 'Commercial Vehicle',
    'rd bldng m': 'Commercial Vehicle',
    'gas t': 'Commercial Vehicle',
    'boom crane': 'Commercial Vehicle',
    'pallet jac': 'Utility Vehicle',
    'skidsteerl': 'Utility Vehicle',
    'man l': 'Commercial Vehicle',
    'emt': 'Emergency Vehicle',
    'skid': 'Utility Vehicle',
    'tugge': 'Commercial Vehicle',
    'sciss': 'Utility Vehicle',
    'e-ska': 'Two-wheeler',
    'spec-': 'Other',
    'razor': 'Two-wheeler',
    'mo-pe': 'Two-wheeler',
    'tcr': 'Other',
    'tra/r': 'Other',
    'bump': 'Other',
    'train': 'Other',
    'detac': 'Other',
    'ip': 'Other',
    'jlg l': 'Commercial Vehicle',
    'cat32': 'Other',
    'man b': 'Commercial Vehicle',
    'van c': 'Commercial Vehicle',
    'campe': 'Passenger Vehicle',
    'c7c': 'Other',
    'speci': 'Other',
    'towin': 'Commercial Vehicle',
    'post': 'Commercial Vehicle',
    'mtriz': 'Other',
    'nyc b': 'Commercial Vehicle',
    'enclo': 'Other',
    'mopen': 'Other',
    'crwzk': 'Other',
    'u-tru': 'Truck',
    'nv ca': 'Commercial Vehicle',
    't650': 'Utility Vehicle',
    'vms t': 'Other',
    'nv150': 'Commercial Vehicle',
    'laund': 'Commercial Vehicle',
    'waste': 'Commercial Vehicle',
    'tkp': 'Other',
    'scava': 'Utility Vehicle',
    'unnko': 'Other',
    'bed': 'Other',
    'expre': 'Other',
    's/sp': 'Other',
    'harve': 'Other',
    'pch': 'Other',
    'oml/': 'Other',
    'e': 'Other',
    "gov't": 'Other',
    'uspst': 'Commercial Vehicle',
    'fre t': 'Other',
    'dig-i': 'Other',
    'anbul': 'Other',
    'axo': 'Other',
    'transit va': 'Commercial Vehicle',
    'e/bik': 'Two-wheeler',
    'subn/': 'Commercial Vehicle',
    'nd': 'Other',
    'milli': 'Other',
    'ems h': 'Emergency Vehicle',
    'bobby': 'Other',
    'ken': 'Other',
    'tour': 'Passenger Vehicle',
    'utll': 'Other',
    'cate': 'Other',
    'porta': 'Other',
    'objec': 'Other',
    'wc': 'Other',
    'hotdo': 'Other',
    '(ceme': 'Other',
    'mot s': 'Other',
    'lp': 'Other',
    'uber': 'Other',
    'veh l': 'Other',
    'trash': 'Commercial Vehicle',
    'spc p': 'Other',
    'unk,': 'Other',
    'shcoo': 'Other',
    'cb534': 'Other',
    'whbl': 'Other',
    'ryder': 'Other',
    'sudan': 'Other',
    'hook': 'Other',
    'trial': 'Other',
    'van f': 'Commercial Vehicle',
    'van`': 'Commercial Vehicle',
    'jlg b': 'Commercial Vehicle',
    'cat 3': 'Other',
    'vant': 'Commercial Vehicle',
    'gmc v': 'Commercial Vehicle',
    'vol': 'Other',
    'tlc v': 'Commercial Vehicle',
    'dept': 'Other',
    'tandu': 'Other',
    'dumpster': 'Commercial Vehicle',
    'ud': 'Other',
    'scaff': 'Utility Vehicle',
    'red,': 'Other',
    'cat 4': 'Other',
    'humme': 'Other',
    'trlpm': 'Other',
    'fortl': 'Other',
    'bus m': 'Passenger Vehicle',
    'u.s p': 'Commercial Vehicle',
    'sbn': 'Other',
    'light towe': 'Other',
    'wanc': 'Other',
    'clean': 'Other',
    'yll p': 'Other',
    'movie': 'Other',
    'dot v': 'Commercial Vehicle',
    'uliti': 'Other',
    'impal': 'Other',
    'nyc s': 'Commercial Vehicle',
    'peter': 'Other',
    'foot': 'Other',
    'tr/c': 'Other',
    'del t': 'Other',
    'wesco': 'Other',
    'bus y': 'Passenger Vehicle',
    'u.s.p': 'Other',
    'drone': 'Other',
    'unk t': 'Other',
    'genie': 'Other',
    'ladd': 'Other',
    'mac 1': 'Other',
    'dep v': 'Other',
    'dlev': 'Other',
    'unkwn': 'Other',
    'tuck': 'Other',
    'sen': 'Other',
    'e250': 'Commercial Vehicle',
    'big r': 'Other',
    'speac': 'Other',
    'ct': 'Other',
    'llv': 'Commercial Vehicle',
    'rmp v': 'Other',
    'mp': 'Other',
    'foor': 'Other',
    'mta t': 'Commercial Vehicle',
    'pz': 'Other',
    'subn-': 'Commercial Vehicle',
    'uk': 'Other'
}

# use vehicle_categories1 to replace values in VEHICLE_TYPE_CODE_1, VEHICLE_TYPE_CODE_2, VEHICLE_TYPE_CODE_3, VEHICLE_TYPE_CODE_4, VEHICLE_TYPE_CODE_5
for i in range(1, 6):
    df['VEHICLE_TYPE_CODE_'+str(i)] = df['VEHICLE_TYPE_CODE_'+str(i)].replace(vehicle_categories1)

vehicle_categories2 = {
    'Passenger Vehicle': [
        '2 dr sedan', '3-door', '4 dr sedan', '4-door', '4dr', '4door', '4dsd',
        '5', '50 cc moto', '50cc scoot', '50cc mini', '600aj', '7', '8x20',
        'a-one', 'accee', 'access a r', 'airport', 'alumi', 'amabu', 'amb',
        'ambluance', 'ambu', 'ambulance', 'ambulette', 'amubl', 'amubulance',
        'amula', 'amulance', 'app c', 'appor', 'apurp', 'arcimoto', 'armored truck',
        'attac', 'b5-44', 'back hoe', 'barri', 'bicycle', 'bk', 'black', 'blue',
        'blue chevy', 'boat', 'bob c', 'bobcat', 'bobcat for', 'bobcat/for', 'broom',
        'brown', 'bs', 'budget tru', 'bus', 'buss', 'cargo van', 'car/suv', 'chev',
        'chevr', 'chevrolet', 'churc', 'city mta b', 'city vehic', 'city owned',
        'cmix', 'cmixer', 'cms-t', 'co', 'collection', 'com', 'com t', 'com trans',
        'com.', 'comm trk', 'comm truck', 'comm van', 'comm vehic', 'comm food',
        'commmercial', 'commerical', 'commm', 'commu', 'compa', 'con ed tru',
        'concrete m', 'const', 'constructi', 'contr', 'contructio', 'conv', 'coupe',
        'courier va', 'd/v wb', 'd/v wb', 'dart bike', 'delivery', 'deliv', 'delv',
        'delv br', 'delv wh', 'delv.', 'delvi', 'delvr', 'dept van #', 'drill rig',
        'dsny', 'dsny garba', 'dsny truck', 'dsny sanit', 'dsny sweep', 'dump truck',
        'dumps', 'dumpt', 'dumptruck', 'dunba', 'e bike', 'e com', 'e pas', 'e revel sc',
        'e scooter', 'e wheelcha', 'e.m.s', 'e350', 'e450', 'ebike', 'econoline',
        'ele motorc', 'elec', 'elec.', 'elec. unic', 'elecr', 'elect', 'electric b',
        'electric c', 'electric m', 'electric s', 'eletr', 'emergancy', 'emergency',
        'ems', 'ems ambula', 'ems bus', 'ems fdny b', 'ems truck', 'ems t', 'engi',
        'enterprise', 'epo', 'es', 'esu rep', 'esu t', 'exp', 'ez go', 'farm vehicle',
        'fd engine', 'fd fi', 'fd la', 'fd ny', 'fd pickup', 'fd tr', 'fd truck',
        'fdny', 'fdny #226', 'fdny ambu', 'fdny ambul', 'fdny chief', 'fdny ems v',
        'fdny emt', 'fdny engin', 'fdny firet', 'fdny lader', 'fdny picku', 'fdny rig',
        'fdny super', 'fdny vehic', 'fdny- fire', 'fdny285 en', 'feder', 'federal ex',
        'fedex', 'fire', 'fire bus', 'fire engin', 'fire truck', 'fire turck', 'firer',
        'firetruck', 'fled', 'fleet', 'fllet', 'fltrl', 'foglift', 'food truck',
        'food vende', 'ford', 'ford ambul', 'ford econo', 'ford f-150', 'ford sprin',
        'ford super', 'ford trans', 'ford two t', 'ford van', 'ford-tcn', 'forklift',
        'forklift t', 'fre', 'freig', 'freight', 'freight va', 'freightlin', 'freih',
        'frht', 'frht trail', 'frht vehic', 'frht-spr', 'frieg', 'frieghtlin',
        'front end', 'front-load', 'g   scl', 'g  co', 'g amb', 'g com', 'g omr',
        'g pas', 'g psd', 'g sem', 'g tow', 'g1', 'g1`', 'garab', 'garba', 'gas s',
        'gator', 'ge/sc', 'geico', 'gen  ambul', 'genui', 'glben', 'glnen',
        'gov vehic', 'govt', 'gray', 'greeb', 'green', 'grumm', 'gspc', 'gth-1056',
        'garage', 'garbage', 'garbage or refuse', 'gene', 'glass rack', 'go kart',
        'golf car', 'golf cart', 'golf kart', 'golfcart', 'gov', 'gov v', 'gov vehicl',
        'gov', 'govenment', 'government', 'go', 'gr hs', 'grey', 'h/w c', 'hand',
        'haul for h', 'hd', 'hd to', 'hdc', 'heavy', 'heavy truc', 'heil', 'hertz ram',
        'hi ta', 'hino', 'hoe-l', 'home made', 'hoverboard', 'hwh', 'hwy c', 'hyund',
        'ice c', 'ice cream', 'industrial', 'inte truck', 'inter', 'internatio', 'intl',
        'in line sk', 'jcb40', 'jeep', 'jetski', 'john', 'john deere', 'johnd',
        'johndeere', 'junst', 'kenwo', 'kme', 'kme/f', 'kp160', 'kubot', 'kw tr',
        'ladder', 'ladder co', 'large com veh(6 or more tires)', 'lawn', 'lawnmower',
        'lc', 'lcom', 'left scene', 'liebh', 'light', 'limo', 'limo/', 'limou',
        'lit direct', 'llv mail t', 'lma']
    }

# use corrections_vehicles1 dictionary to create a mapping of the 'VEHICLE TYPE CODE 1' column
for key, value in vehicle_categories2.items():
    df['VEHICLE_TYPE_CODE_1'] = df['VEHICLE_TYPE_CODE_1'].replace(value, key)
    df['VEHICLE_TYPE_CODE_2'] = df['VEHICLE_TYPE_CODE_2'].replace(value, key)
    df['VEHICLE_TYPE_CODE_3'] = df['VEHICLE_TYPE_CODE_3'].replace(value, key)
    df['VEHICLE_TYPE_CODE_4'] = df['VEHICLE_TYPE_CODE_4'].replace(value, key)
    df['VEHICLE_TYPE_CODE_5'] = df['VEHICLE_TYPE_CODE_5'].replace(value, key)

vehicle_categories3 = {
    "Passenger Vehicle": [
            'passenger vehicle', 'pas v', 'combinatio', 'petit cab', 'van (trans', 'pass van', 'livery vehicle', 'marked rmp',
            'police veh', 'x amb', 'mail carri', 'omnibus', 'razor scoo', 'mini vahn', 'ford couri', 'small bus', 'manual sco',
            'horse draw', 'motorhome', "passenger", "standing s", "ford f150", "yellow bus", 'passanger',
            "caravan", "car t", "club", "club", "van s", "van u", "sierra", "suv /", "ridgeline",
            'toyot', 'pas 5', 'burg', 'semi-truck', 'rv motorho', 'van ford'
        ],
        "Truck": [
            'ref box tr', 'tow-truck', 'box van', 'refr', 'sweeper', 'fire truvk', 'bread truc', 'del truck', 'truck w/tr',
            'waste truc', 'boxtruck', 'dot truck', 'fd ambulan', 'fdny utili', 'truck/bus', "flatbed to", "pick-up", "gmc ecom",
            "box p", "box m", "box mail t", "c45 boc tr", "dumpster t", "flatbed truck", "freighntli", "hilow",
            "hyster for", "jlg m", "jj150t-4a", "penske box", "pickup sl", "pickup w/t", "pish", "qbe i", "rolloff",
            "salt", "savana van", "scooter bi", "trc m", "trcic", "trk", "truc", "truck", "towe", "utyli", "utility truck",
            "usps box t", "white box", "fire rig t", "uhaul van", "gmc t", "dual", "saltspread"
        ],
        "Commercial Vehicle": [
            'commer veh', 'ford ff', 'fdny mecha', 'fd ambulan', 'usps vehic', 'usps #6530', 'liabitiy', 'fdny mecha',
            "small com veh(4 tires)", "mta van", "mta transi", "nyc fdny #", "traffic to",
            "box m", "box p", "box mail t", "c45 boc tr", "commercial truck", "delivery van", "distributo", "fdny bus",
            "food trail", "freighntli", "j1", "lumbe", "metrotech", "mi/fu", "penske box", "pickup sl", "police van",
            "private am", "tank truck", "vendor foo", "workcart", "rental van", "trialer", "uhal renta"
        ],
        "Two-wheeler": [
            'cm', 'gas moped', 'moped', 'e motorcyc', 'razor150 m', 'razor scoo', 'pedal bike', "moped", "revel mope",
            'mopped', "escoo", "e- scooter", "motor. sco", "moto-scoot", "scooter bi", "scooter/mo", "scooter si", "scooter (g",
            "siting mop", "telehandle", "tracktor t", "utility van", "bmw moped", "dirt-"
        ],
        "Emergency Vehicle": [
            'mta v', 'marked rmp', 'police veh', 'x amb', 'fd ambulan', 'fdny utili', 'fire truvk', 'emergency',
            "fdny bus", "fdny ferra", "police van", "hurse", 'Emergency Vehicle'
        ],
        "Utility Vehicle": [
            'towma', 'deiv', 'scom', 'left', 'coll', 'no/bu', 'ups m', 'not i', 'whit', 'isuzu', 'hi-lo', 'van e', 'ukn',
            'lmtv', 'flat-', 'tc', 'us go', 'tlc p', 'lsa', 'vanet', 'u-hal', 'c1', 'high', 'frh', 'g scl', 'mac', 'p psd',
            'govt p/u t', 'dot', 'ele. unicy', 'ref box tr', 'del truck', 'usps vehic', 'dot truck', 'refr', 'box van',
            'truck w/tr', 'utility vehicle', "utility truck", "van s", "van u", "workcart", "station wa",
            "unattached", 'us goverme'
        ],
        "Other": [
            'suret', 'con e', 'com v', 'yale', 'commerc veh', 'chassis &', 'motorizeds', 'gas powered', 'pepsi deli', 'emi- trail',
            'mooper', 'gas powered', 'utility van', 'govt p/u t', 'van (trans', 'reg', 'revel', 'pickup tow', 'transport',
            'utv bobcat', 'metro tran', 'lim', 'yale fork', 'unkwown', 'usps #6530', 'flywing mo', 'one wheel',
            "military", "manpower s", "access-a-r", "electronic", "lsv", "commerial", "va", "commericia",
            'small com veh(4 tires) ', "cement mix", "chevy van", "distributo", "dot tow tr", "dot safety", "excabator", "flywing", "food trail",
            "ford ec2", "jlg ultra", "ne/fl", "nycha fork", "postoffice", "private am", "ram comm.", "red", "scooter/mo",
            "seagrave t", "trailer fl", "truck", "unk.", "unk l", "unknw", "unkowm", "usps post", "vehic", "white dodg",
            "white ford", "wstr", "x", "x com", "xnypd signa", 'utilt', 'dlvr', 'sanat', 'nypd signa', 'naa', 'c-1', 'tt',
            'com/a', 'm/a', 'off r', 'vms sign', 'f350', 'rolle', 'metal', 'small trac', 'luv', 'vend', 'platf', 'offic',
            'lull', 'potal', 'red m', 'tilla', 'mac f', 'yps', 'scho', 'silve', 'db', 'refg/', 'palle', 'gmc', 'srf',
            'omc', 'dumpe', 'doosk', 'vas', 'wg', 'rolli', 'qmz', 'ynk', 'p/v', 'ecoli', 'hi lo', 'quad', 'vam',
            'dei v', 'vn', 'refrg', 'nyc g', 'fed', 'roro', 'yw', 'n?a', 'refq', 'deagr', 'unkl', 'usps#', 'parke',
            'uni', 'unlno', 'unk/l', 'dlr', 'ref g', 'trt', 'van/r', 'nyc-s', 'payloader', 'black mope', 'straight t',
            'fd apparat', 'ic', 'tl trailer', 'moped gas', 'uhaul trai', 'cat escaba', 'white work', 'maintenanc',
            'mta esu ve', 'push cart', 'rear end', 'p/sh yw', 'subn/ambul', 'electrict', 'mta bus 40', 'semitraile',
            'fdny 331 k', 'u haul tra', 'trailer/tr', 'electricun', 'camper', 'c40', 'vehicle tr', "olm", "short"
        ]
    }

# use corrections_vehicles1 dictionary to create a mapping of the 'VEHICLE TYPE CODE 1' column
for key, value in vehicle_categories3.items():
    df['VEHICLE_TYPE_CODE_1'] = df['VEHICLE_TYPE_CODE_1'].replace(value, key)
    df['VEHICLE_TYPE_CODE_2'] = df['VEHICLE_TYPE_CODE_2'].replace(value, key)
    df['VEHICLE_TYPE_CODE_3'] = df['VEHICLE_TYPE_CODE_3'].replace(value, key)
    df['VEHICLE_TYPE_CODE_4'] = df['VEHICLE_TYPE_CODE_4'].replace(value, key)
    df['VEHICLE_TYPE_CODE_5'] = df['VEHICLE_TYPE_CODE_5'].replace(value, key)

# lower case contributing_factor_vehicle_1, contributing_factor_vehicle_2, contributing_factor_vehicle_3, contributing_factor_vehicle_4, contributing_factor_vehicle_5
df['CONTRIBUTING_FACTOR_VEHICLE_1'] = df['CONTRIBUTING_FACTOR_VEHICLE_1'].str.lower()
df['CONTRIBUTING_FACTOR_VEHICLE_2'] = df['CONTRIBUTING_FACTOR_VEHICLE_2'].str.lower()
df['CONTRIBUTING_FACTOR_VEHICLE_3'] = df['CONTRIBUTING_FACTOR_VEHICLE_3'].str.lower()
df['CONTRIBUTING_FACTOR_VEHICLE_4'] = df['CONTRIBUTING_FACTOR_VEHICLE_4'].str.lower()
df['CONTRIBUTING_FACTOR_VEHICLE_5'] = df['CONTRIBUTING_FACTOR_VEHICLE_5'].str.lower()

# corrections contributing_factor_vehicle
corrections_vehicles = {
    '80': 'Unspecified',
    'accelerator defective': 'Vehicle Defect',
    'aggressive driving/road rage': 'Aggressive Driving',
    'alcohol involvement': 'Driving Under Influence',
    'animals action': 'Animal Action',
    'backing unsafely': 'Unsafe Backing',
    'brakes defective': 'Vehicle Defect',
    'cell phone (hand-held)': 'Distracted Driving',
    'cell phone (hands-free)': 'Distracted Driving',
    'driver inattention/distraction': 'Distracted Driving',
    'driver inexperience': 'Driver Error',
    'driverless/runaway vehicle': 'Vehicle Defect',
    'drugs (illegal)': 'Driving Under Influence',
    'eating or drinking': 'Distracted Driving',
    'failure to keep right': 'Traffic Violation',
    'failure to yield right-of-way': 'Traffic Violation',
    'fatigued/drowsy': 'Driver Error',
    'fell asleep': 'Driver Error',
    'following too closely': 'Tailgating',
    'glare': 'Environmental Factor',
    'headlights defective': 'Vehicle Defect',
    'illnes': 'Medical Condition',
    'illness': 'Medical Condition',
    'lane marking improper/inadequate': 'Infrastructure Issue',
    'listening/using headphones': 'Distracted Driving',
    'lost consciousness': 'Medical Condition',
    'obstruction/debris': 'Environmental Factor',
    'other electronic device': 'Distracted Driving',
    'other lighting defects': 'Vehicle Defect',
    'other vehicular': 'Other',
    'outside car distraction': 'Distracted Driving',
    'oversized vehicle': 'Vehicle Type',
    'passenger distraction': 'Distracted Driving',
    'passing or lane usage improper': 'Traffic Violation',
    'passing too closely': 'Unsafe Passing',
    'pavement defective': 'Infrastructure Issue',
    'pavement slippery': 'Environmental Factor',
    'pedestrian/bicyclist/other pedestrian error/confusion': 'Pedestrian/Bicyclist Error',
    'physical disability': 'Medical Condition',
    'prescription medication': 'Medical Condition',
    'reaction to other uninvolved vehicle': 'Driver Error',
    'reaction to uninvolved vehicle': 'Driver Error',
    'shoulders defective/improper': 'Infrastructure Issue',
    'steering failure': 'Vehicle Defect',
    'texting': 'Distracted Driving',
    'tinted windows': 'Vehicle Modification',
    'tire failure/inadequate': 'Vehicle Defect',
    'tow hitch defective': 'Vehicle Defect',
    'traffic control device improper/non-working': 'Traffic Violation',
    'traffic control disregarded': 'Traffic Violation',
    'turning improperly': 'Traffic Violation',
    'unsafe lane changing': 'Unsafe Maneuver',
    'unsafe speed': 'Speeding',
    'unspecified': 'Unspecified',
    'using on board navigation device': 'Distracted Driving',
    'vehicle vandalism': 'Criminal Activity',
    'view obstructed/limited': 'Environmental Factor',
    'windshield inadequate': 'Vehicle Defect'
}

# iterate through the dictionary and replace the old categories with the new categories in contributing_factor_vehicle_1, contributing_factor_vehicle_2, contributing_factor_vehicle_3, contributing_factor_vehicle_4, contributing_factor_vehicle_5
df['CONTRIBUTING_FACTOR_VEHICLE_1'] = df['CONTRIBUTING_FACTOR_VEHICLE_1'].replace(corrections_vehicles)
df['CONTRIBUTING_FACTOR_VEHICLE_2'] = df['CONTRIBUTING_FACTOR_VEHICLE_2'].replace(corrections_vehicles)
df['CONTRIBUTING_FACTOR_VEHICLE_3'] = df['CONTRIBUTING_FACTOR_VEHICLE_3'].replace(corrections_vehicles)
df['CONTRIBUTING_FACTOR_VEHICLE_4'] = df['CONTRIBUTING_FACTOR_VEHICLE_4'].replace(corrections_vehicles)
df['CONTRIBUTING_FACTOR_VEHICLE_5'] = df['CONTRIBUTING_FACTOR_VEHICLE_5'].replace(corrections_vehicles)

# reset the index
df.reset_index(drop=True, inplace=True)

# Divide df into two dataframes: first one will have the first 10 columns plus COLLISION_ID, and the second one will have the rest of the columns
df1 = df.iloc[:, :3]
# add the COLLISION_ID column to df1
df1['COLLISION_ID'] = df['COLLISION_ID']

#df2
df2 = df.iloc[:, 3:]

# save df1 and df2 to csv files
df1.to_csv('cleaned_data1.csv', index=False)
df2.to_csv('cleaned_data2.csv', index=False)

# save df to a csv file named cleaned_data.csv
df.to_csv('cleaned_data.csv', index=False)